Nova.booting((Vue, router, store) => {
    // Vue.component('index-nova-cms-blocks', require('./components/IndexField'))
    Vue.component('detail-nova-cms-blocks', require('./components/DetailField'))
    Vue.component('detail-nova-cms-blocks-group', require('./components/DetailGroup'))
    Vue.component('form-nova-cms-blocks', require('./components/FormField'))
    Vue.component('form-nova-cms-blocks-group', require('./components/FormGroup'))
    Vue.component('flexible-drop-menu', require('./components/OriginalDropMenu'))
    Vue.component('delete-flexible-content-group-modal', require('./components/DeleteGroupModal'))
    Vue.component('icon-arrow-down', require('./components/icons/ArrowDown'))
    Vue.component('icon-arrow-up', require('./components/icons/ArrowUp'))
    Vue.component('icon-plus-square', require('./components/icons/PlusSquare'))
    Vue.component('icon-minus-square', require('./components/icons/MinusSquare'))
})
